version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4575:4575"
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=sns:4575,sqs:4576
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
